
spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
logging :
  level:
    org.springframework.data.r2dbc.core.DatabaseClient: DEBUG


