spring:
  web:
    resources:
      add-mappings: true
  application:
    name: "spring features"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-password
    properties:
      "[mail.smtp.connection timeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.write timeout]": 5000
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8081
  servlet:
    context-path: "/spring-app"
